## Dataset used:

* Found Victorian rental dataset via https://discover.data.vic.gov.au/dataset/rental-report-quarterly-data-tables

## 1. Load data into Python (Jupyter Notebook)

* Loaded Excel workbook
* Navigated multiple sheets
* Chose correct analytical table (Table 12)
* Explored data just to get a feel

In [1]:
import pandas as pd

df = pd.read_excel("../data/rental_data.xlsx")

In [2]:
df.head()

,Homes Victoria Rental Report - September Quarter 2025,Unnamed: 1
0,NaN,Contents
1,Worksheet,Title
2,Front page,Rent Indices at a glance
3,Table 1,Median rents and metropolitan Melbourne and re...
4,Figure 1,Metropolitan Rent Index and Regional Rent Inde...

In [3]:
df.columns

Index(['Homes Victoria Rental Report - September Quarter 2025', 'Unnamed: 1'], dtype='str')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Homes Victoria Rental Report - September Quarter 2025  34 non-null     str
 1   Unnamed: 1                                             34 non-null     str
dtypes: str(2)
memory usage: 708.0 bytes

In [5]:
df.describe()

       Homes Victoria Rental Report - September Quarter 2025 Unnamed: 1
count                                                  34            34
unique                                                 34            34
top                                             Worksheet      Contents
freq                                                    1             1

In [6]:
excel_file = pd.ExcelFile("../data/rental_data.xlsx")

excel_file.sheet_names

['Contents',
 'Front page',
 'Table 1',
 'Figure 1',
 'Table 2',
 'Table 3',
 'Figure 2',
 'Figure 3',
 'Table 4',
 'Table 5',
 'Table 6',
 'Figure 4',
 'Figure 5a',
 'Figure 5b',
 'Table 7',
 'Table 8',
 'Figure 6',
 'Figure 7',
 'Figure 8',
 'Table 9',
 'Table 10',
 'Table 11',
 'Figure 9a',
 'Figure 9b',
 'Table 12',
 'Table 13',
 'Table 14',
 'Table 15',
 'Fig 1 source',
 'Fig 4 source',
 'Fig 6 source',
 'Fig 7 source',
 'Fig 8 source']

In [7]:
df = pd.read_excel(
    "../data/rental_data.xlsx",
    sheet_name="Table 12"
)

df.head(20)

,Table 12: Moving annual median rents for suburbs and towns by major property type,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43
0,NaN,NaN,1 Bed Flat,NaN,NaN,NaN,NaN,NaN,NaN,2 Bed Flat,...,NaN,NaN,NaN,4 Bed House,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Count,Median,Ann % Ch,Percentile 25,Percentile 75,5 yr % ch,Ave 5 yr % ch,Count,...,Percentile 75,5 yr % ch,Ave 5 yr % ch,Count,Median,Ann % Ch,Percentile 25,Percentile 75,5 yr % ch,Ave 5 yr % ch
2,Inner Melbourne,Albert Park-Middle Park-West St Kilda,176,450,0.022727,405,500,0.285714,0.057143,144,...,1310,0.210526,0.042105,35,1400,-0.066667,1200,1650,0.025641,0.005128
3,NaN,Armadale,188,450,-0.021739,420,535,0.285714,0.057143,282,...,1300,0.222222,0.044444,14,1738,0.287407,1250,2100,0.511304,0.102261
4,NaN,Carlton North,37,430,0.04878,400,470,0.228571,0.045714,69,...,1050,0.225806,0.045161,12,1225,-0.012097,1100,1550,0.262887,0.052577
5,NaN,Carlton-Parkville,1023,500,0.041667,435,580,0.315789,0.063158,1235,...,1200,0.266667,0.053333,29,1100,-0.083333,1000,1250,0.157895,0.031579
6,NaN,CBD-St Kilda Rd,6274,560,0.018182,500,650,0.4,0.08,6605,...,-,-,-,-,-,-,-,-,-,-
7,NaN,Collingwood-Abbotsford,631,520,0.04,490,555,0.268293,0.053659,702,...,1075,0.1875,0.0375,13,1200,0.090909,1000,1400,0.466993,0.093399
8,NaN,Docklands,1240,600,0.071429,550,650,0.395349,0.07907,1512,...,-,-,-,-,-,-,-,-,-,-
9,NaN,East Melbourne,165,520,0.04,470,575,0.3,0.06,177,...,1300,-0.102041,-0.020408,-,-,-,-,-,-,-
10,NaN,East St Kilda,433,425,0.0625,390,470,0.307692,0.061538,712,...,980,0.2,0.04,23,1100,-0.079498,1000,1350,0.294118,0.058824
11,NaN,Elwood,331,450,0.046512,400,500,0.323529,0.064706,610,...,1200,0.303571,0.060714,26,1500,-0.119718,1199,1750,0.160093,0.032019
12,NaN,Fitzroy,204,528,0.005714,423,590,0.32,0.064,223,...,1300,0.27907,0.055814,-,-,-,-,-,-,-
13,NaN,Fitzroy North-Clifton Hill,239,500,0.111111,430,625,0.428571,0.085714,267,...,1150,0.330667,0.066133,46,1295,-0.01145,1100,1500,0.363158,0.072632
14,NaN,Flemington-Kensington,500,470,0.175,395,552,0.287671,0.057534,657,...,820,0.169231,0.033846,31,945,0.038462,850,1025,0.3125,0.0625
15,NaN,North Melbourne-West Melbourne,1239,525,0.071429,460,580,0.3125,0.0625,1239,...,940,0.218571,0.043714,22,1080,-0.018182,950,1300,0.213483,0.042697
16,NaN,Port Melbourne,218,550,0.047619,500,600,0.235955,0.047191,370,...,1125,0.225,0.045,54,1125,-0.1,1050,1250,0.071429,0.014286
17,NaN,Prahran-Windsor,803,460,0.033708,390,520,0.243243,0.048649,679,...,1150,0.234177,0.046835,29,1350,0,1015,1595,0.551724,0.110345
18,NaN,Richmond-Burnley,871,510,0.030303,450,560,0.275,0.055,881,...,1175,0.289062,0.057813,42,1315,0.095833,1150,1500,0.315,0.063
19,NaN,South Melbourne,408,548,0.033962,499,600,0.37,0.074,485,...,1100,0.117647,0.023529,-,-,-,-,-,-,-

## 2. Clean data 

* multi-level headers
* messy Excel structure
* renamed columns
* forward-filled regions
* removed “-” values
* converted to numeric types
* built `df_clean`

In [8]:
# reload while skipping title row. tells pandas: use TWO header rows skip the giant title row. Results in cleaner multi-level column names.

df = pd.read_excel(
    "../data/rental_data.xlsx",
    sheet_name="Table 12",
    header=[0,1],
    skiprows=1
)

df.head()

  Unnamed: 0_level_0                     Unnamed: 1_level_0 1 Bed Flat         \
  Unnamed: 0_level_1                     Unnamed: 1_level_1      Count Median
0    Inner Melbourne  Albert Park-Middle Park-West St Kilda        176    450
1                NaN                               Armadale        188    450
2                NaN                          Carlton North         37    430
3                NaN                      Carlton-Parkville       1023    500
4                NaN                        CBD-St Kilda Rd       6274    560

                                                                2 Bed Flat  \
   Ann % Ch Percentile 25 Percentile 75 5 yr % ch Ave 5 yr % ch      Count
0  0.022727           405           500  0.285714      0.057143        144
1 -0.021739           420           535  0.285714      0.057143        282
2   0.04878           400           470  0.228571      0.045714         69
3  0.041667           435           580  0.315789      0.063158       1235
4  0.018182           500           650       0.4          0.08       6605

   ...   3 Bed House                         4 Bed House                   \
   ... Percentile 75 5 yr % ch Ave 5 yr % ch       Count Median  Ann % Ch
0  ...          1310  0.210526      0.042105          35   1400 -0.066667
1  ...          1300  0.222222      0.044444          14   1738  0.287407
2  ...          1050  0.225806      0.045161          12   1225 -0.012097
3  ...          1200  0.266667      0.053333          29   1100 -0.083333
4  ...             -         -             -           -      -         -


  Percentile 25 Percentile 75 5 yr % ch Ave 5 yr % ch
0          1200          1650  0.025641      0.005128
1          1250          2100  0.511304      0.102261
2          1100          1550  0.262887      0.052577
3          1000          1250  0.157895      0.031579
4             -             -         -             -

[5 rows x 44 columns]

In [9]:
# forward fill regions. NaNs mean "same region as above"

df.iloc[:,0] = df.iloc[:,0].ffill()

In [10]:
# rename columns

df = df.rename(columns={
    df.columns[0]: "Region",
    df.columns[1]: "Suburb"
})

In [11]:
df.head()

  Unnamed: 0_level_0                     Unnamed: 1_level_0 1 Bed Flat         \
  Unnamed: 0_level_1                     Unnamed: 1_level_1      Count Median
0    Inner Melbourne  Albert Park-Middle Park-West St Kilda        176    450
1    Inner Melbourne                               Armadale        188    450
2    Inner Melbourne                          Carlton North         37    430
3    Inner Melbourne                      Carlton-Parkville       1023    500
4    Inner Melbourne                        CBD-St Kilda Rd       6274    560

                                                                2 Bed Flat  \
   Ann % Ch Percentile 25 Percentile 75 5 yr % ch Ave 5 yr % ch      Count
0  0.022727           405           500  0.285714      0.057143        144
1 -0.021739           420           535  0.285714      0.057143        282
2   0.04878           400           470  0.228571      0.045714         69
3  0.041667           435           580  0.315789      0.063158       1235
4  0.018182           500           650       0.4          0.08       6605

   ...   3 Bed House                         4 Bed House                   \
   ... Percentile 75 5 yr % ch Ave 5 yr % ch       Count Median  Ann % Ch
0  ...          1310  0.210526      0.042105          35   1400 -0.066667
1  ...          1300  0.222222      0.044444          14   1738  0.287407
2  ...          1050  0.225806      0.045161          12   1225 -0.012097
3  ...          1200  0.266667      0.053333          29   1100 -0.083333
4  ...             -         -             -           -      -         -


  Percentile 25 Percentile 75 5 yr % ch Ave 5 yr % ch
0          1200          1650  0.025641      0.005128
1          1250          2100  0.511304      0.102261
2          1100          1550  0.262887      0.052577
3          1000          1250  0.157895      0.031579
4             -             -         -             -

[5 rows x 44 columns]

In [12]:
# cleaner column names. ('1 Bed Flat', 'Median') to 1 Bed Flat_Median

df.columns = [
    f"{col1}_{col2}" if "Unnamed" not in str(col1) else col2
    for col1, col2 in df.columns
]

In [13]:
df.head()

,Unnamed: 0_level_1,Unnamed: 1_level_1,1 Bed Flat_Count,1 Bed Flat_Median,1 Bed Flat_Ann % Ch,1 Bed Flat_Percentile 25,1 Bed Flat_Percentile 75,1 Bed Flat_5 yr % ch,1 Bed Flat_Ave 5 yr % ch,2 Bed Flat_Count,...,3 Bed House_Percentile 75,3 Bed House_5 yr % ch,3 Bed House_Ave 5 yr % ch,4 Bed House_Count,4 Bed House_Median,4 Bed House_Ann % Ch,4 Bed House_Percentile 25,4 Bed House_Percentile 75,4 Bed House_5 yr % ch,4 Bed House_Ave 5 yr % ch
0,Inner Melbourne,Albert Park-Middle Park-West St Kilda,176,450,0.022727,405,500,0.285714,0.057143,144,...,1310,0.210526,0.042105,35,1400,-0.066667,1200,1650,0.025641,0.005128
1,Inner Melbourne,Armadale,188,450,-0.021739,420,535,0.285714,0.057143,282,...,1300,0.222222,0.044444,14,1738,0.287407,1250,2100,0.511304,0.102261
2,Inner Melbourne,Carlton North,37,430,0.04878,400,470,0.228571,0.045714,69,...,1050,0.225806,0.045161,12,1225,-0.012097,1100,1550,0.262887,0.052577
3,Inner Melbourne,Carlton-Parkville,1023,500,0.041667,435,580,0.315789,0.063158,1235,...,1200,0.266667,0.053333,29,1100,-0.083333,1000,1250,0.157895,0.031579
4,Inner Melbourne,CBD-St Kilda Rd,6274,560,0.018182,500,650,0.4,0.08,6605,...,-,-,-,-,-,-,-,-,-,-

In [14]:
# rename columns 

df = df.rename(columns={
    "Unnamed: 0_level_1": "Region",
    "Unnamed: 1_level_1": "Suburb"
})

In [15]:
df.head()

,Region,Suburb,1 Bed Flat_Count,1 Bed Flat_Median,1 Bed Flat_Ann % Ch,1 Bed Flat_Percentile 25,1 Bed Flat_Percentile 75,1 Bed Flat_5 yr % ch,1 Bed Flat_Ave 5 yr % ch,2 Bed Flat_Count,...,3 Bed House_Percentile 75,3 Bed House_5 yr % ch,3 Bed House_Ave 5 yr % ch,4 Bed House_Count,4 Bed House_Median,4 Bed House_Ann % Ch,4 Bed House_Percentile 25,4 Bed House_Percentile 75,4 Bed House_5 yr % ch,4 Bed House_Ave 5 yr % ch
0,Inner Melbourne,Albert Park-Middle Park-West St Kilda,176,450,0.022727,405,500,0.285714,0.057143,144,...,1310,0.210526,0.042105,35,1400,-0.066667,1200,1650,0.025641,0.005128
1,Inner Melbourne,Armadale,188,450,-0.021739,420,535,0.285714,0.057143,282,...,1300,0.222222,0.044444,14,1738,0.287407,1250,2100,0.511304,0.102261
2,Inner Melbourne,Carlton North,37,430,0.04878,400,470,0.228571,0.045714,69,...,1050,0.225806,0.045161,12,1225,-0.012097,1100,1550,0.262887,0.052577
3,Inner Melbourne,Carlton-Parkville,1023,500,0.041667,435,580,0.315789,0.063158,1235,...,1200,0.266667,0.053333,29,1100,-0.083333,1000,1250,0.157895,0.031579
4,Inner Melbourne,CBD-St Kilda Rd,6274,560,0.018182,500,650,0.4,0.08,6605,...,-,-,-,-,-,-,-,-,-,-

In [16]:
df.columns.tolist()

['Region',
 'Suburb',
 '1 Bed Flat_Count',
 '1 Bed Flat_Median',
 '1 Bed Flat_Ann % Ch',
 '1 Bed Flat_Percentile 25',
 '1 Bed Flat_Percentile 75',
 '1 Bed Flat_5 yr % ch',
 '1 Bed Flat_Ave 5 yr % ch',
 '2 Bed Flat_Count',
 '2 Bed Flat_Median',
 '2 Bed Flat_Ann % Ch',
 '2 Bed Flat_Percentile 25',
 '2 Bed Flat_Percentile 75',
 '2 Bed Flat_5 yr % ch',
 '2 Bed Flat_Ave 5 yr % ch',
 '3 Bed Flat_Count',
 '3 Bed Flat_Median',
 '3 Bed Flat_Ann % Ch',
 '3 Bed Flat_Percentile 25',
 '3 Bed Flat_Percentile 75',
 '3 Bed Flat_5 yr % ch',
 '3 Bed Flat_Ave 5 yr % ch',
 '2 Bed House_Count',
 '2 Bed House_Median',
 '2 Bed House_Ann % Ch',
 '2 Bed House_Percentile 25',
 '2 Bed House_Percentile 75',
 '2 Bed House_5 yr % ch',
 '2 Bed House_Ave 5 yr % ch',
 '3 Bed House_Count',
 '3 Bed House_Median',
 '3 Bed House_Ann % Ch',
 '3 Bed House_Percentile 25',
 '3 Bed House_Percentile 75',
 '3 Bed House_5 yr % ch',
 '3 Bed House_Ave 5 yr % ch',
 '4 Bed House_Count',
 '4 Bed House_Median',
 '4 Bed House_Ann % Ch',
 '4 Bed House_Percentile 25',
 '4 Bed House_Percentile 75',
 '4 Bed House_5 yr % ch',
 '4 Bed House_Ave 5 yr % ch']

In [17]:
# For 4 Bed House_median, have to converts valid numbers → numeric values. And invalid values like "-" -> "NaN"

df["4 Bed House_Median"] = pd.to_numeric(
    df["4 Bed House_Median"],
    errors="coerce"
)

In [18]:
df[["Suburb", "4 Bed House_Median"]].sort_values(
    by="4 Bed House_Median",
    ascending=False
).head(10)

                                   Suburb  4 Bed House_Median
21                                 Toorak              1875.0
1                                Armadale              1738.0
18                            South Yarra              1700.0
43                               Brighton              1650.0
9                                  Elwood              1500.0
35                               Hawthorn              1500.0
50                                Malvern              1400.0
0   Albert Park-Middle Park-West St Kilda              1400.0
15                        Prahran-Windsor              1350.0
16                       Richmond-Burnley              1315.0

In [19]:
# Also the case with 2 Bed Flat_Median. Contains values like "-"

df["2 Bed Flat_Median"] = pd.to_numeric(
    df["2 Bed Flat_Median"],
    errors="coerce"
)

In [20]:
df.groupby("Region")["2 Bed Flat_Median"].mean()

Region
Ballarat                   354.000000
Bendigo                    389.600000
Geelong                    423.125000
Inner Eastern Melbourne    582.277778
Inner Melbourne            673.217391
Mornington Peninsula       484.666667
North Eastern Melbourne    517.307692
North Western Melbourne    511.153846
Other Regional Centres     374.909091
Outer Eastern Melbourne    507.888889
Outer Western Melbourne    474.846154
South Eastern Melbourne    476.444444
Southern Melbourne         598.571429
Name: 2 Bed Flat_Median, dtype: float64

In [21]:
# Replace "-" with NaN

df = df.replace("-", None)

In [22]:
# Convert all numeric columns

for col in df.columns[2:]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 44 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Region                     159 non-null    str
 1   Suburb                     159 non-null    str
 2   1 Bed Flat_Count           144 non-null    float64
 3   1 Bed Flat_Median          144 non-null    float64
 4   1 Bed Flat_Ann % Ch        144 non-null    float64
 5   1 Bed Flat_Percentile 25   144 non-null    float64
 6   1 Bed Flat_Percentile 75   144 non-null    float64
 7   1 Bed Flat_5 yr % ch       144 non-null    float64
 8   1 Bed Flat_Ave 5 yr % ch   144 non-null    float64
 9   2 Bed Flat_Count           158 non-null    float64
 10  2 Bed Flat_Median          158 non-null    float64
 11  2 Bed Flat_Ann % Ch        158 non-null    float64
 12  2 Bed Flat_Percentile 25   158 non-null    float64
 13  2 Bed Flat_Percentile 75   158 non-null    float64
 14  2 Bed Flat_5 yr % ch       158 non-null    float64
 15  2 Bed Flat_Ave 5 yr % ch   158 non-null    float64
 16  3 Bed Flat_Count           149 non-null    float64
 17  3 Bed Flat_Median          149 non-null    float64
 18  3 Bed Flat_Ann % Ch        149 non-null    float64
 19  3 Bed Flat_Percentile 25   149 non-null    float64
 20  3 Bed Flat_Percentile 75   149 non-null    float64
 21  3 Bed Flat_5 yr % ch       149 non-null    float64
 22  3 Bed Flat_Ave 5 yr % ch   149 non-null    float64
 23  2 Bed House_Count          154 non-null    float64
 24  2 Bed House_Median         154 non-null    float64
 25  2 Bed House_Ann % Ch       154 non-null    float64
 26  2 Bed House_Percentile 25  154 non-null    float64
 27  2 Bed House_Percentile 75  154 non-null    float64
 28  2 Bed House_5 yr % ch      154 non-null    float64
 29  2 Bed House_Ave 5 yr % ch  154 non-null    float64
 30  3 Bed House_Count          156 non-null    float64
 31  3 Bed House_Median         156 non-null    float64
 32  3 Bed House_Ann % Ch       156 non-null    float64
 33  3 Bed House_Percentile 25  156 non-null    float64
 34  3 Bed House_Percentile 75  156 non-null    float64
 35  3 Bed House_5 yr % ch      156 non-null    float64
 36  3 Bed House_Ave 5 yr % ch  156 non-null    float64
 37  4 Bed House_Count          153 non-null    float64
 38  4 Bed House_Median         153 non-null    float64
 39  4 Bed House_Ann % Ch       153 non-null    float64
 40  4 Bed House_Percentile 25  153 non-null    float64
 41  4 Bed House_Percentile 75  153 non-null    float64
 42  4 Bed House_5 yr % ch      153 non-null    float64
 43  4 Bed House_Ave 5 yr % ch  153 non-null    float64
dtypes: float64(42), str(2)
memory usage: 54.8 KB

In [24]:
# Calculate total number of missing values

df.isna().sum().sort_values(ascending=False)

1 Bed Flat_Median            15
1 Bed Flat_Count             15
1 Bed Flat_Percentile 25     15
1 Bed Flat_Ann % Ch          15
1 Bed Flat_Ave 5 yr % ch     15
1 Bed Flat_5 yr % ch         15
1 Bed Flat_Percentile 75     15
3 Bed Flat_5 yr % ch         10
3 Bed Flat_Count             10
3 Bed Flat_Median            10
3 Bed Flat_Ann % Ch          10
3 Bed Flat_Percentile 25     10
3 Bed Flat_Percentile 75     10
3 Bed Flat_Ave 5 yr % ch     10
4 Bed House_5 yr % ch         6
4 Bed House_Median            6
4 Bed House_Ave 5 yr % ch     6
4 Bed House_Count             6
4 Bed House_Ann % Ch          6
4 Bed House_Percentile 25     6
4 Bed House_Percentile 75     6
2 Bed House_Ave 5 yr % ch     5
2 Bed House_Ann % Ch          5
2 Bed House_5 yr % ch         5
2 Bed House_Percentile 75     5
2 Bed House_Percentile 25     5
2 Bed House_Median            5
2 Bed House_Count             5
3 Bed House_Median            3
3 Bed House_Count             3
3 Bed House_Percentile 25     3
3 Bed House_Ave 5 yr % ch     3
3 Bed House_5 yr % ch         3
3 Bed House_Percentile 75     3
3 Bed House_Ann % Ch          3
2 Bed Flat_Count              1
2 Bed Flat_Ave 5 yr % ch      1
2 Bed Flat_5 yr % ch          1
2 Bed Flat_Ann % Ch           1
2 Bed Flat_Median             1
2 Bed Flat_Percentile 75      1
2 Bed Flat_Percentile 25      1
Suburb                        0
Region                        0
dtype: int64

In [25]:
# Create df_clean with only Median columns

keep_cols = [
    "Region",
    "Suburb",
    "1 Bed Flat_Median",
    "2 Bed Flat_Median",
    "3 Bed House_Median",
    "4 Bed House_Median"
]

df_clean = df[keep_cols]

In [26]:
# Long format (melt)

df_melted = df_clean.melt(
    id_vars=["Region", "Suburb"],
    var_name="Property Type",
    value_name="Median Rent"
)

In [27]:
df_clean.sort_values("4 Bed House_Median").head(10)

,Region,Suburb,1 Bed Flat_Median,2 Bed Flat_Median,3 Bed House_Median,4 Bed House_Median
129,Ballarat,Sebastopol-Delacombe,300.0,350.0,400.0,455.0
141,Other Regional Centres,Hamilton,260.0,320.0,390.0,460.0
131,Ballarat,Total,285.0,350.0,410.0,461.0
58,Outer Western Melbourne,Melton,350.0,365.0,420.0,470.0
127,Ballarat,Ballarat,285.0,360.0,410.0,475.0
128,Ballarat,Mount Clear-Buninyong,285.0,360.0,430.0,480.0
130,Ballarat,Wendouree-Alfredton,285.0,350.0,410.0,480.0
120,Geelong,Corio,320.0,380.0,420.0,485.0
145,Other Regional Centres,Morwell,275.0,320.0,400.0,493.0
142,Other Regional Centres,Horsham,250.0,320.0,430.0,520.0

In [28]:
# My df_clean simply does NOT include "2 Bed House_Median". I actually do have "2 Bed House_Median" in the original dataset, but it was simply not included in df_clean earlier. That was issue.

df_clean.columns.tolist()

['Region',
 'Suburb',
 '1 Bed Flat_Median',
 '2 Bed Flat_Median',
 '3 Bed House_Median',
 '4 Bed House_Median']

In [29]:
# strip whitespace

df_clean.columns = df_clean.columns.str.strip()

In [30]:
df_clean.columns.tolist()

['Region',
 'Suburb',
 '1 Bed Flat_Median',
 '2 Bed Flat_Median',
 '3 Bed House_Median',
 '4 Bed House_Median']

In [31]:
[c for c in df_clean.columns if "House" in c]

['3 Bed House_Median', '4 Bed House_Median']

In [32]:
[c for c in df.columns if "2 Bed" in c]

['2 Bed Flat_Count',
 '2 Bed Flat_Median',
 '2 Bed Flat_Ann % Ch',
 '2 Bed Flat_Percentile 25',
 '2 Bed Flat_Percentile 75',
 '2 Bed Flat_5 yr % ch',
 '2 Bed Flat_Ave 5 yr % ch',
 '2 Bed House_Count',
 '2 Bed House_Median',
 '2 Bed House_Ann % Ch',
 '2 Bed House_Percentile 25',
 '2 Bed House_Percentile 75',
 '2 Bed House_5 yr % ch',
 '2 Bed House_Ave 5 yr % ch']

In [33]:
# Fix: rebuild df_clean properly. Then make sure everything is numeric.

df_clean = df[[
    "Region",
    "Suburb",
    "1 Bed Flat_Median",
    "2 Bed Flat_Median",
    "2 Bed House_Median",
    "3 Bed House_Median",
    "4 Bed House_Median"
]]

In [34]:
# Make sure everything is numeric:

for col in df_clean.columns[2:]:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

In [35]:
df_clean.groupby("Region")["2 Bed House_Median"].mean()

Region
Ballarat                   363.000000
Bendigo                    430.600000
Geelong                    439.375000
Inner Eastern Melbourne    589.777778
Inner Melbourne            749.200000
Mornington Peninsula       499.333333
North Eastern Melbourne    547.923077
North Western Melbourne    550.000000
Other Regional Centres     402.428571
Outer Eastern Melbourne    522.555556
Outer Western Melbourne    497.538462
South Eastern Melbourne    483.888889
Southern Melbourne         645.071429
Name: 2 Bed House_Median, dtype: float64

In [36]:
df_clean.groupby("Region")[[
    "1 Bed Flat_Median",
    "2 Bed Flat_Median",
    "3 Bed House_Median",
    "4 Bed House_Median"
]].mean()

,1 Bed Flat_Median,2 Bed Flat_Median,3 Bed House_Median,4 Bed House_Median
Region,,,,
Ballarat,288.000000,354.000000,412.000000,470.200000
Bendigo,334.000000,389.600000,479.000000,560.000000
Geelong,338.285714,423.125000,495.625000,587.500000
Inner Eastern Melbourne,467.222222,582.277778,710.222222,950.333333
Inner Melbourne,500.260870,673.217391,1003.550000,1311.941176
Mornington Peninsula,368.600000,484.666667,590.833333,740.000000
North Eastern Melbourne,414.583333,517.307692,646.384615,807.000000
North Western Melbourne,408.500000,511.153846,639.785714,782.428571
Other Regional Centres,279.947368,374.909091,475.136364,576.727273
Outer Eastern Melbourne,371.857143,507.888889,596.888889,705.000000
Outer Western Melbourne,389.833333,474.846154,567.307692,677.153846
South Eastern Melbourne,365.428571,476.444444,550.000000,639.777778
Southern Melbourne,433.785714,598.571429,829.285714,1156.785714

In [ ]:
# Removing records with these regions since they're not in Melbourne
regions_to_remove = ['Geelong', 'Ballarat', 'Bendigo', 'Other Regional Centres']

df_clean = df_clean[~df_clean['Region'].isin(regions_to_remove)]

In [ ]:
print(df['Region'].unique())

## 3. Basic analysis 

* groupby operations
* sorting (top suburbs)
* summary stats
* sanity checks

In [37]:
df_clean.columns

Index(['Region', 'Suburb', '1 Bed Flat_Median', '2 Bed Flat_Median',
       '2 Bed House_Median', '3 Bed House_Median', '4 Bed House_Median'],
      dtype='str')

In [38]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Region              159 non-null    str
 1   Suburb              159 non-null    str
 2   1 Bed Flat_Median   144 non-null    float64
 3   2 Bed Flat_Median   158 non-null    float64
 4   2 Bed House_Median  154 non-null    float64
 5   3 Bed House_Median  156 non-null    float64
 6   4 Bed House_Median  153 non-null    float64
dtypes: float64(5), str(2)
memory usage: 8.8 KB

In [39]:
df_clean.isna().sum()

Region                 0
Suburb                 0
1 Bed Flat_Median     15
2 Bed Flat_Median      1
2 Bed House_Median     5
3 Bed House_Median     3
4 Bed House_Median     6
dtype: int64

In [40]:
df_clean.describe()

,1 Bed Flat_Median,2 Bed Flat_Median,2 Bed House_Median,3 Bed House_Median,4 Bed House_Median
count,144.000000,158.000000,154.000000,156.000000,153.000000
mean,399.500000,512.696203,541.298701,653.461538,816.562092
std,83.479154,106.590156,123.073395,194.725030,298.796001
min,245.000000,310.000000,330.000000,390.000000,455.000000
25%,337.500000,432.500000,450.000000,500.000000,580.000000
50%,400.000000,510.000000,520.000000,600.000000,725.000000
75%,456.250000,590.000000,611.250000,751.250000,1000.000000
max,600.000000,763.000000,875.000000,1250.000000,1875.000000

In [41]:
df_clean.dtypes

Region                    str
Suburb                    str
1 Bed Flat_Median     float64
2 Bed Flat_Median     float64
2 Bed House_Median    float64
3 Bed House_Median    float64
4 Bed House_Median    float64
dtype: object

In [42]:
df_clean.duplicated().sum()

np.int64(0)


##5. Exploratory Analaysis

In [43]:
# Most expensive suburbs

df_clean.sort_values("4 Bed House_Median", ascending=False).head(10)

,Region,Suburb,1 Bed Flat_Median,2 Bed Flat_Median,2 Bed House_Median,3 Bed House_Median,4 Bed House_Median
21,Inner Melbourne,Toorak,445.0,650.0,695.0,1250.0,1875.0
1,Inner Melbourne,Armadale,450.0,650.0,830.0,1100.0,1738.0
18,Inner Melbourne,South Yarra,500.0,700.0,780.0,1100.0,1700.0
43,Southern Melbourne,Brighton,498.0,680.0,760.0,1150.0,1650.0
9,Inner Melbourne,Elwood,450.0,608.0,795.0,1095.0,1500.0
35,Inner Eastern Melbourne,Hawthorn,450.0,600.0,710.0,950.0,1500.0
50,Southern Melbourne,Malvern,450.0,600.0,790.0,1000.0,1400.0
0,Inner Melbourne,Albert Park-Middle Park-West St Kilda,450.0,643.0,760.0,1150.0,1400.0
15,Inner Melbourne,Prahran-Windsor,460.0,650.0,775.0,975.0,1350.0
16,Inner Melbourne,Richmond-Burnley,510.0,700.0,750.0,990.0,1315.0

In [44]:
# Compare property types

df_clean[[
    "1 Bed Flat_Median",
    "2 Bed Flat_Median",
    "3 Bed House_Median",
    "4 Bed House_Median"
]].mean()

1 Bed Flat_Median     399.500000
2 Bed Flat_Median     512.696203
3 Bed House_Median    653.461538
4 Bed House_Median    816.562092
dtype: float64

In [45]:
# Region comparison

df_clean.groupby("Region")["3 Bed House_Median"].mean()

Region
Ballarat                    412.000000
Bendigo                     479.000000
Geelong                     495.625000
Inner Eastern Melbourne     710.222222
Inner Melbourne            1003.550000
Mornington Peninsula        590.833333
North Eastern Melbourne     646.384615
North Western Melbourne     639.785714
Other Regional Centres      475.136364
Outer Eastern Melbourne     596.888889
Outer Western Melbourne     567.307692
South Eastern Melbourne     550.000000
Southern Melbourne          829.285714
Name: 3 Bed House_Median, dtype: float64

## 4. Save cleaned dataset 

* dataset ready for visualisations

In [46]:
df_clean.to_csv("../data/clean_rental_data.csv", index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

## 5. Inserting to Database (PostgreSQL)

In [47]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Ethan1data237@localhost:5432/melbourne_rentals"
)

In [48]:
df_clean.to_sql(
    "rental_prices",
    engine,
    if_exists="replace",
    index=False
)

print("Cleaned dataset inserted successfully.")

Cleaned dataset inserted successfully.